controller_joint_names: ['', 'FR_crotch_joint', 'FR_thigh_joint', 'FR_calf_joint', 'FL_crotch_joint', 'FL_thigh_joint', 'FL_calf_joint', 'HL_crotch_joint', 'HL_thigh_joint', 'HR_crotch_joint', 'HR_thigh_joint', 'HR_calf_joint', ]
