task_name: ${task.name}
algo_name: ${train.name}
test: False


num_envs: 64
seed: 42

physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'gpu'
# device for running physics simulation
sim_device: 'cuda:0'
# device to run RL
rl_device: 'cuda:0'
graphics_device_id: 0
terrain_type: plane

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread

printreward: false
# disables rendering
headless: False
#render
force_render: True

checkpoint: ''
logdir: 'logs/'
log: '1'

defaults:
  - task: VehicleTerrain
  - train: ${task}PPO
  - hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .